### ISSUE TITLE
[Refactor] JWT 코드 리팩토링 및 성능 향상, 에러 처리

### ISSUE THREAD

**Issue by taek2222** [BUTTERFLY-CODE-NEAR/Butterfly_BE#74]
## 📄 설명
JWT 코드 전체적인 리팩토링을 한다.

## ✅ TO-DO
- [x] JWT 코드 가독성 향상을 위한 리팩토링
- [x] 성능 향상을 위해 Member 찾는 DB 로직 삭제
- [x] 에러 처리 강화

## 🌱 예상기간
9월 12일 ~ 9월 12일
