### ISSUE TITLE
[Refactor] 쿠키 NULL 에러 처리 및 Auth 컨트롤러 리팩토링

### ISSUE THREAD

**Issue by taek2222** [BUTTERFLY-CODE-NEAR/Butterfly_BE#81]
## 📄 설명
쿠키 체크 부분에서 발생하는 NullPonintException 에러 보완 및 Auth 컨트롤러 응답을 보완한다.
추가로, JWT 실험 컨트롤러 하나 임시 생성한다.

## ✅ TO-DO
- [x] 쿠키 NULL 값 보완
- [x] Auth 컨트롤러 응답 보완
- [x] JWT 실험 컨트롤러 임시 생성

## 🌱 예상기간
9월 14일 ~ 9월 14일
